---

- set_fact:
    src_dir_parent: "/usr/local/src"
    openssl_install_dir: /var/lib/python_sre_openssl
    openssl_version: 1.1.1d
    conf_autobot: /etc/sre/sre.conf

- name: Python version short 3.8.3 --> 3.8
  set_fact:
    python_version_abbreviated: "{{ '.'.join(python_version.split('.')[:2])}}"

- set_fact:
    src_dir: "{{ src_dir_parent }}/Python-{{python_version}}"
    broker_port: "{{ broker_port | default(1883) }}"
    http_port: "{{ broker_port | default(8520) }}"
    http_address: "{{ http_address | default('0.0.0.0') }}"

