---

- name: Check if "{{ conf_autobot }}" exists
  stat:
    path: "{{ conf_autobot }}"
  register: stat_result

- name: provide {{ conf_autobot }}
  template:
    src: ../files/sre.conf
    dest: "{{ conf_autobot }}"
  when: not stat_result.stat.exists

- name: update {{ conf_autobot }}
  command: /usr/bin/python3
  args:
    stdin: |
      from pathlib import Path
      import json

      file = Path("{{ conf_autobot }}")
      content = eval(file.read_text())
      bots = eval("{{ bots }}")
      content['bots-paths'] = bots
      file.write_text(json.dumps(content, indent=4))

- name: deploy configurations
  copy:
    content: "{{ item.value }}"
    dest: "{{ item.name }}"
  with_items: "{{ configs }}"
