---

- name: Check if "{{ conf_autobot }}" exists
  stat:
    path: "{{ conf_autobot }}"
  register: stat_result

- name: provide {{ conf_autobot }}
  template:
    src: ../files/sre.conf
    dest: "{{ conf_autobot }}"
  when: not stat_result.stat.exists

- name: update {{ conf_autobot }}
  shell:
    cmd: sre add-bot-path '{{ item.path }}'
  with_items: "{{ bots }}"

- name: deploy configurations
  copy:
    content: "{{ item.value }}"
    dest: "{{ item.name }}"
  with_items: "{{ configs }}"
