---
- name: install sre as a service
  shell:
    chdir: "{{ venv_dir }}"
    cmd: |
      sre install
      systemctl restart sre

- name: start sre systemd service
  systemd: state=started name=sre daemon_reload=yes

- name: Make sure autobot service is running
  systemd: state=started name=sre