---
- include_tasks: 1000-facts.yml

- include_tasks: 1500-clean.yml

- include_tasks: 2000-install-python.yml

- include_tasks: 3000-configuration.yml

- include_tasks: 3500-clone-bot-repos.yml

- include_tasks: 3600-install-reqs.yml

- include_tasks: 4000-start-service.yml
